{% set name = "dwave-preprocessing" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-preprocessing/archive/refs/tags/{{ version }}.tar.gz
  sha256: e73f9fcb9210351f02d3982cd497b7fcd2eb935275ba1f2ef798fb87805ef699

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy 1.20                             # [build_platform != target_platform and py<310]
    - numpy                                  # [build_platform != target_platform and py>=310]
    - dimod >=0.12.0rc1,<0.13.0              # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - dimod >=0.12.0rc1,<0.13.0
    - numpy 1.20  # [py<310]
    - numpy       # [py>=310]
    - pip
    - python
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - dimod >=0.12.0rc1,<0.13.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - dwave.preprocessing
  commands:
    - pip check
    - cd tests
    - python -m unittest
  requires:
    - pip
  source_files:
    - tests

about:
  home: https://github.com/dwavesystems/dwave-preprocessing
  summary: An API for preprocessing tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
