{% set name = "dwave-preprocessing" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-preprocessing/archive/refs/tags/{{ version }}.tar.gz
  sha256: 176f9146dd4be71d04a89902c5c1ef1b4ceb3d7b504b0767991cfe3a760fd90d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - dimod >=0.12.17                        # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3,<4
    - dimod >=0.12.17
    - numpy
    - pip
    - python
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - dimod >=0.12.6,<0.13.0
    - python

test:
  imports:
    - dwave.preprocessing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-preprocessing
  summary: An API for preprocessing tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
