{% set name = "dwave-preprocessing" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-preprocessing/archive/refs/tags/{{ version }}.tar.gz
  sha256: 04ff8937b131af3520d4197f256c4ba68cad0783af131c57ce20083d3f36fad3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - dimod ==0.11.0
    - numpy >=1.21.0,<2.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - dimod >=0.11.0,<0.12.0
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - dwave.preprocessing
  commands:
    - pip check
    - cd tests
    - python -m unittest
  requires:
    - pip
  source_files:
    - tests

about:
  home: https://github.com/dwavesystems/dwave-preprocessing
  summary: An API for preprocessing tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
