{% set name = "dwave-preprocessing" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-preprocessing/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8bb418ad8775378d6f751d8ccae9a4a208fab1fe493a2a09d4ba2a2576d2c08b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - dimod >=0.12.17                        # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3,<4
    - dimod >=0.12.17
    - numpy
    - pip
    - python
    - setuptools >=46.4.0
    - wheel >=0.30.0
  run:
    - dimod >=0.12.6,<0.13.0
    - python

test:
  imports:
    - dwave.preprocessing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-preprocessing
  summary: An API for preprocessing tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
